// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyAllRequestFormats(arg1) {
  return window['go']['main']['App']['CopyAllRequestFormats'](arg1);
}

export function CopyRequest(arg1, arg2) {
  return window['go']['main']['App']['CopyRequest'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRequest(arg1) {
  return window['go']['main']['App']['CreateRequest'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function DeleteRequestHistoryItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequestHistoryItem'](arg1, arg2);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function GetFolders(arg1) {
  return window['go']['main']['App']['GetFolders'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetRequestHistory(arg1) {
  return window['go']['main']['App']['GetRequestHistory'](arg1);
}

export function GetRequests(arg1) {
  return window['go']['main']['App']['GetRequests'](arg1);
}

export function GetTelemetryEnabled() {
  return window['go']['main']['App']['GetTelemetryEnabled']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function MoveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2, arg3);
}

export function ReportError(arg1, arg2) {
  return window['go']['main']['App']['ReportError'](arg1, arg2);
}

export function ReportUsageEvent(arg1, arg2) {
  return window['go']['main']['App']['ReportUsageEvent'](arg1, arg2);
}

export function SetTelemetryEnabled(arg1) {
  return window['go']['main']['App']['SetTelemetryEnabled'](arg1);
}

export function UpdateFolder(arg1) {
  return window['go']['main']['App']['UpdateFolder'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateRequest(arg1) {
  return window['go']['main']['App']['UpdateRequest'](arg1);
}
